using UnityEngine;

public class Grabber : MonoBehaviour
{
    public GameObject selectedObject;

    public void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {
            if(selectedObject == null)
            {
                RaycastHit hit = CastRay();

                if (hit.collider!=null)
                {
                    if(!hit.collider.CompareTag("drag"))
                    {
                        return; 
                    }

                    selectedObject = hit.collider.gameObject;
                    Cursor.visible = false; 
                }
            }    
        }
        else
            {
                Vector3 position = new Vector3(Input.mousePosition.x, Input.mousePosition.y, Camera.main.WorldToScreenPoint(selectedObject.transform.position).z);
                Vector3 worldPosition = Camera.main.ScreenToWorldPoint(position);
                selectedObject.transform.position = new Vector3(worldPosition.x, .25f, worldPosition.z);

                selectedObject = null;
                Cursor.visible = true;
            }
        {
            if(selectedObject != null)
            {
                Vector3 position = new Vector3(Input.mousePosition.x, Input.mousePosition.y, Camera.main.WorldToScreenPoint(selectedObject.transform.position).z);
                Vector3 worldPosition = Camera.main.ScreenToWorldPoint(position);
                selectedObject.transform.position = new Vector3(worldPosition.x, .25f, worldPosition.z);
            }
        }
        if (selectedObject != null) 
     {

     }   
    }

    public RaycastHit CastRay()
    {
        Vector3 screenMousePosFar = new Vector3( Input.mousePosition.x, Input.mousePosition.y, Camera.main.farClipPlane);
        Vector3 screenMousePosNear = new Vector3( Input.mousePosition.x, Input.mousePosition.y, Camera.main.farClipPlane);
        Vector3 worldMousePosFar = Camera.main.ScreenToWorldPoint(screenMousePosFar);
        Vector3 worldMousePosNear = Camera.main.ScreenToWorldPoint(screenMousePosNear);
        RaycastHit hit;
        Physics.Raycast(worldMousePosNear, worldMousePosFar - worldMousePosNear, out hit);

        return hit;
    }
}  



